name: edge_venv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - python=3.12.5=h5148396_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.33.0
      - addict==2.4.0
      - affine==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - alembic==1.13.2
      - altair==5.3.0
      - aniso8601==9.0.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==2.15.8
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - audioread==3.0.1
      - autopep8==2.0.0
      - av==12.3.0
      - babel==2.15.0
      - bandit==1.7.9
      - beautifulsoup4==4.12.3
      - black==24.4.2
      - bleach==6.1.0
      - blinker==1.8.2
      - blis==0.7.11
      - boto3==1.34.147
      - botocore==1.34.147
      - braceexpand==0.1.7
      - cachetools==5.4.0
      - captum==0.7.0
      - catalogue==2.0.10
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.18.1
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - comet-ml==3.44.2
      - comm==0.2.2
      - confection==0.1.5
      - configobj==5.0.8
      - contourpy==1.2.1
      - cupy-cuda12x==12.3.0
      - cupy-wheel==12.3.0
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.20.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.14.4
      - defusedxml==0.7.1
      - delayed-image==0.3.1
      - deprecated==1.2.14
      - diffusers==0.29.2
      - dill==0.3.8
      - distinctipy==1.3.4
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - dodgy==0.2.1
      - dulwich==0.22.1
      - easydict==1.13
      - entrypoints==0.4
      - evaluate==0.4.2
      - everett==3.1.0
      - executing==2.0.1
      - fastai==2.7.15
      - fastcore==1.5.54
      - fastdownload==0.0.7
      - fastjsonschema==2.20.0
      - fastprogress==1.0.3
      - fastrlock==0.8.2
      - filelock==3.15.4
      - flake8==5.0.4
      - flake8-fixme==1.1.1
      - flake8-functions-names==0.4.0
      - flake8-polyfill==1.0.2
      - flake8-variables-names==0.0.6
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - grpcio==1.65.1
      - gunicorn==22.0.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.1
      - humanfriendly==10.0
      - idna==3.7
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - imgaug==0.4.0
      - importlib-metadata==7.1.0
      - inquirerpy==0.3.4
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - isort==5.13.2
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - kwarray==0.6.19
      - kwcoco==0.8.2
      - kwimage==0.10.1
      - langcodes==3.4.0
      - language-data==1.2.0
      - lazy-loader==0.4
      - lazy-object-proxy==1.10.0
      - librosa==0.10.2.post1
      - lightning==2.3.3
      - lightning-utilities==0.11.6
      - llvmlite==0.43.0
      - mako==1.3.5
      - marisa-trie==1.2.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - mlflow==2.14.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy==1.11.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - nltk==3.8.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.1
      - onnxruntime==1.18.1
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.5.5.64
      - opentelemetry-api==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parse==1.20.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pbr==6.0.0
      - pep8-naming==0.10.0
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==10.4.0
      - platformdirs==4.2.2
      - pooch==1.8.2
      - portalocker==2.10.1
      - preshed==3.0.9
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - prospector==1.10.3
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycodestyle==2.9.1
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydeck==0.9.1
      - pydocstyle==6.3.0
      - pydub==0.25.1
      - pyflakes==2.5.0
      - pygments==2.18.0
      - pylama==8.4.1
      - pylint==2.17.7
      - pylint-celery==0.3
      - pylint-django==2.5.3
      - pylint-flask==0.6
      - pylint-plugin-utils==0.7
      - pyparsing==3.1.2
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-lightning==2.3.3
      - pytorch-metric-learning==2.5.0
      - pytorch-triton==3.0.0+dedb7bdf33
      - pytorchvideo==0.1.5
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - qudida==0.0.4
      - querystring-parser==1.2.4
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - requirements-detector==1.2.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rouge-score==0.1.2
      - rpds-py==0.19.0
      - s3transfer==0.10.2
      - sacremoses==0.1.1
      - safer==4.12.3
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - scriptconfig==0.7.15
      - semantic-version==2.10.0
      - semver==3.0.2
      - send2trash==1.8.3
      - sentence-transformers==3.0.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.10.0
      - seqeval==1.2.2
      - setoptconf-tmp==0.3.1
      - setproctitle==1.3.3
      - shapely==2.0.5
      - shellingham==1.5.4
      - simplejson==3.19.2
      - simpletransformers==0.70.1
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.3.7
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-llm==0.7.2
      - spacy-loggers==1.0.5
      - spacy-lookups-data==1.0.5
      - sqlalchemy==2.0.31
      - sqlparse==0.5.1
      - srsly==2.4.8
      - stack-data==0.6.3
      - stevedore==5.2.0
      - streamlit==1.36.0
      - sudachidict-core==20240716
      - sudachipy==0.6.8
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tifffile==2024.7.21
      - timm==1.0.7
      - tinycss2==1.3.0
      - tokenize-rt==5.2.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.13.0
      - toolz==0.12.1
      - torch==2.3.1
      - torch-fidelity==0.3.0
      - torch-tb-profiler==0.4.3
      - torchaudio==2.3.1
      - torchdata==0.7.1
      - torchinfo==1.8.0
      - torchmetrics==1.4.0.post0
      - torchtext==0.18.0
      - torchvision==0.18.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.43.1
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - ubelt==1.3.6
      - uri-template==1.3.0
      - uritools==4.0.3
      - urllib3==2.2.2
      - wandb==0.17.5
      - wasabi==1.1.3
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.6.0
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - wurlitzer==3.1.1
      - xarray==2024.6.0
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.19.2
prefix: /home/sugimoto/miniconda3/envs/edge_venv
